## Auto-generated by the Fivetran Ingestion Portal — do not hand-edit.
## Source system: test7
## Environment:    dev
## Generated:      2026-07-22T10:52:32.021Z
##
## One module block per sync-frequency tier. Fivetran only supports a single
## sync frequency per connector, so tables needing different schedules are
## split across separate connectors (created earlier in the wizard) — this
## file just applies each connector's schema config and schedule.
module "test7_60min_connector" {
  source = "git::https://github.com/chandu5012/vdp-fivetran-terraform-module.git?ref=v1"

  connector_id           = "short_retrieve"
  schema_change_handling = "ALLOW_COLUMNS"
  sync_frequency_minutes = 60

  tables = [
    {
      source_schema = "public"
      source_table  = "inventory"
      target_table  = "inventory"
    },
    {
      source_schema = "public"
      source_table  = "product_catalog"
      target_table  = "product_catalog"
    },
    {
      source_schema = "public"
      source_table  = "test_tr"
      target_table  = "test_tr"
    },
  ]
}
